services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecret
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://942f-103-129-16-33.ngrok-free.app
      - GENERIC_TIMEZONE=Europe/Rome
      - TZ=Asia/Bangkok
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=90
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom

volumes:
  n8n_data:
